---
repo-name: peripherals-kinetic-platform
categories:
- Service Management
- Request Management
- CRM
- DevOps
- Ticketing
display-name: Kinetic Platform
manufacturer: Kinetic Data
product:
description: Kinetic Data is an Enterprise Workflow platform that connects human and technology interactions across systems of record at scale. Built on the core tenets of security, scalability and flexibility, prospects are empowered to transform their entire organization into a highly efficient, automated reality that reduces workload, cost of service delivery and risk. Technically savvy users leverage Kinetic’s framework and tools to build out applications and introduce workflow automation which solve thorny, complex problems at scale.